services:
  bot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container-dev
    network_mode: host
    ports:
      - 8000:8000
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

