version: "3.9"
services:
  bot-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "bot-backend:latest"
    container_name: bot-backend-container
    networks:
      - network-backend
    ports:
      - 8000:8000
    # volumes:
      # - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  network-backend:
    external: true
